name: Simple_TDD_Sample_CI

on:
  push:
    branches: 
      - main
    paths: 
      - '**/Simple_TDD_Sample/**'
      -  '!**/.github/**'
  pull_request:
    branches:
      - main

jobs:
  build:
  
    env:
      target_project: '**/Simple_TDD_Sample/Simple_TDD_Sample.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore $target_project
      
    - name: Build
      run: dotnet build $target_project --no-restore
      
    - name: Test
      run: dotnet test $target_project --no-build --verbosity normal
